AllCops:
  Exclude:
    - "config/**/*"
    - "bin/spring"
    - "Gemfile"
    - "Gemfile.lock"
    - "Rakefile"
    - "test/test_helper.rb"
    - "db/seeds.rb"
    - "db/schema.rb"
    - "app/controllers/application_controller.rb"
    - "app/helpers/application_helper.rb"
    - "app/mailers/application_mailer.rb"
    - "app/models/application_record.rb"
    - "test/**/*"
    - "spec/**/*"

Documentation:
  Enabled: false

Metrics/LineLength:
  Exclude:
    - "spec/**/*"

Style/EmptyMethod:
  Enabled: false
Layout/AlignHash:
  Enabled: false
SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
  EnforcedStyleForEmptyBraces: space
Layout/TrailingWhitespace:
  Enabled: false
AlignParameters:
  EnforcedStyle: with_fixed_indentation
StringLiterals:
  Enabled: false
Style/MethodDefParentheses:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
